### ISSUE TITLE
plot() error

### ISSUE THREAD

**Issue by lwk1542** [VSainteuf/mcssa#2]
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_asarray.py:85: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
Traceback (most recent call last):
  File "C:/Users/lwk15/Documents/GitHub/HY_project/test.py", line 14, in <module>
    mcssa.plot()
  File "C:\Users\lwk15\Documents\GitHub\HY_project\mcssa\mcssa.py", line 214, in plot
    return utils.plot(self, freq_rank)
  File "C:\Users\lwk15\Documents\GitHub\HY_project\mcssa\utils.py", line 273, in plot
    ecolor='k', elinewidth=.5, capsize=2.5)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2561, in errorbar
    **({"data": data} if data is not None else {}), **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 1599, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 3219, in errorbar
    plot_line = (fmt.lower() != 'none')
AttributeError: 'NoneType' object has no attribute 'lower'

Process finished with exit code 1

**Comment by mxshen** [comment]
I met the same problem:
>>> mcssa.plot()
D:\Users\xxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\numpy\core\_asarray.py:83: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Users\xxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mcssa\mcssa.py", line 214, in plot
    return utils.plot(self, freq_rank)
  File "D:\Users\xxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mcssa\utils.py", line 272, in plot
    plt.errorbar(x, y=mean_suro, yerr=errors, fmt=None,
  File "D:\Users\xxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\matplotlib\pyplot.py", line 2524, in errorbar
    return gca().errorbar(
  File "D:\Users\xxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\matplotlib\__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "D:\Users\xxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\matplotlib\axes\_axes.py", line 3172, in errorbar
    plot_line = (fmt.lower() != 'none')
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by VSainteuf** [comment]
Thanks for pointing this out. It could be a Matplotlib version problem, or  a bug in my code, I'll have a look!
Could you tell me with which version of Matplotlib you are running the code ?

**Comment by VSainteuf** [comment]
Can you try running your code using the [plot_error_isue](https://github.com/VSainteuf/mcssa/tree/plot_error_issue) branch?
It fixed the problem on my side, if it works for you guys to I'll merge to the master.

The problem was that the correct way to pass to the `fmt` argument of `plt.errorbar` changed from None to 'none' at some point during the Matplotlib releases.
